version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: unless-stopped

  # Test Management Application
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:5432/${DATABASE_DB}?sslmode=disable
    depends_on:
      - postgres
    restart: unless-stopped
    # Wait for postgres to be ready
    command: >
      sh -c "
        while ! nc -z postgres 5432; do
          echo 'Waiting for postgres...'
          sleep 1
        done
        echo 'PostgreSQL is ready!'
        ./main
      "